#!/bin/bash
echo "Enter Mysql Username : "
read uname
echo "Enter Mysql Password : "
read passwd
for f in *.sql.gz
   do
     filename=$(basename $f .sql.gz)
     echo "Creating DB -- ${filename}"
     mysqladmin -u $uname -p$passwd create  $filename
     echo "DB Created -- ${filename}"
     echo "Started Importing ${f} to ${filename}"
     zcat $f | mysql -u $uname -p$passwd $filename
     echo "Completed Importing ${f} to ${filename}"
done
